"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import os, PyQt4

files = []

for dirname, dirnames, filenames in os.walk('WebKit'):
    for filename in filenames:
        files += [(dirname, [os.path.join(dirname, filename)])]

for dirname, dirnames, filenames in os.walk('images'):
    for filename in filenames:
        files += [(dirname, [os.path.join(dirname, filename)])]

VERSION = "2.0.0"

APP = ['Bungloo.py']
OPTIONS = {
	'argv_emulation': False,
    'iconfile': 'images/Icon.icns',
    'plist': {
        'CFBundleShortVersionString': VERSION,
        'CFBundleIdentifier': "nu.jabs.apps.bungloo",
        'LSMinimumSystemVersion': "10.4",
        'CFBundleURLTypes': [
            {
                'CFBundleURLName': 'nu.jabs.apps.bungloo.handler',
                'CFBundleURLSchemes': ['bungloo']
            }
        ]
    },
    'includes':['PyQt4.QtWebKit', 'PyQt4', 'PyQt4.QtCore', 'PyQt4.QtGui', 'simplejson', 'PyQt4.QtNetwork'],
    'excludes': ['PyQt4.QtDesigner', 'PyQt4.QtOpenGL', 'PyQt4.QtScript', 'PyQt4.QtSql', 'PyQt4.QtTest', 'PyQt4.QtXml', 'PyQt4.phonon'],
    'qt_plugins': 'imageformats',
}

setup(
    app=APP,
    version=VERSION,
    data_files=files,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)

print os.path.dirname(PyQt4.__file__)